
WHEEL_UP  add volume  2
WHEEL_DOWN add volume -2

UP  add volume  2
DOWN add volume -2

Alt+1 set window-scale 0.5
Alt+2 set window-scale 1.0
Alt+3 set window-scale 2.0

F1 cycle-values video-unscaled "no" "yes" 
F2 set video-unscaled "downscale-big"
F3 cycle-values  video-zoom -1 0
F4 cycle-values  video-zoom 1 0
F5 cycle-values scale "nearest" "bilinear"

#F3 cycle-values loop "no" "yes"

ENTER cycle fullscreen
KP_ENTER cycle fullscreen

q cycle pause
Alt+q quit

+  add speed "0.25"; show-text "${speed}"
-  add speed "-0.25"; show-text "${speed}"

RIGHT seek 5
LEFT seek -5


