osd-color="#ffffffff"
osd-border-color="#00000000"
osd-border-size=3

volume=50

osd-duration=2000

osd-msg1=${clock}

loop=no
loop-playlist=inf
af=scaletempo=stride=30
#af=rubberband
no-border

video-unscaled
#osd-scale-by-window=no

#######################################################################
[showcqt-visualizer]
lavfi-complex="[aid1] asplit [ao] [v] ; [v] showwaves=mode=line, format=rgb0 [vo]"
lavfi-complex="[aid1] asplit [ao] [v] ; [v] showwaves=mode=p2p, format=rgb0 [vo]"
lavfi-complex="[aid1] asplit [ao],  compand, showwavespic=s=1024x320, format=rgb0 [vo]"
# add other visualization (showwaves ... etc)

[mpv-visualizer]
# select which visualizer to use
profile=showcqt-visualizer
[extension.wav]
profile=mpv-visualizer
########################################################################
