osd-color="#ffffffff"
osd-border-color="#00000000"
osd-border-size=3

volume=50

osd-duration=2000
osd-msg1=${clock}

loop=no
loop-playlist=inf
af=scaletempo=stride=30
#af=rubberband
no-border

video-unscaled
#osd-scale-by-window=no

script-opts=osc-visibility=always

#######################################################################
[showcqt-visualizer] # showwaves=mode =[p2p|line|cline]
#lavfi-complex="[aid1] asplit [ao] [v] ; [v] showwaves=mode=p2p, format=rgb0 [vo]"
lavfi-complex="[aid1] asplit [ao] [v]; [v]showwavespic=s=1200x320:colors=#545454, format=rgb0 [vo]"
# add other visualization (showwaves ... etc)

[mpv-visualizer]
# select which visualizer to use
profile=showcqt-visualizer
[extension.wav]
profile=mpv-visualizer
[extension.mp3]
profile=mpv-visualizer
[extension.aiff]
profile=mpv-visualizer
[extension.ogg]
profile=mpv-visualizer
[extension.flac]
profile=mpv-visualizer
########################################################################

